## eric-enmsg-filetransferservice image version
global:
  pullSecret:
  registry:
    url: armdocker.rnd.ericsson.se
  ingress:
    enmHost:
  tags:
    deploy_eric_net_ingress_l4:
  vips:
    svc_FM_vip_ipaddress:
    svc_CM_vip_ipaddress:
    svc_PM_vip_ipaddress:
    cm_vip_ipv6address:
    fm_vip_ipv6address:
    svc_FM_vip_ipv6address:
    svc_CM_vip_ipv6address:
    svc_PM_vip_ipv6address:
  enmProperties:
    COM_INF_LDAP_ADMIN_ACCESS:
    COM_INF_LDAP_PORT:
    COM_INF_LDAP_ROOT_SUFFIX:
    COM_INF_LDAP_ADMIN_CN:
    LDAP_ADMIN_CN:
    LDAP_ADMIN_PASSWORD:
    smrs_sftp_port_partition_enable:
    smrs_sftp_securePort:
    postgres_service:
  timezone:
  ip_version: IPv4
productNumber: CXC 174 2129
productRevision: RSTATE
labels: {}
securityPolicy:
  rolename: filetransferservice
# Number of replicas(pods) to deploy
replicas-eric-enmsg-filetransferservice: 1
images:
  eric-enmsg-filetransferservice:
    name: eric-enmsg-filetransferservice
    tag: VERSION
  waitInitContainer:
    enabled: true
    name: eric-enm-init-container
    tag: 1.64.0-32
    command: "[ '/bin/sh', '-c', 'bash /var/tmp/check_service.sh -s gossiprouter-cache,gossiprouter-eap7,jms01,postgres,sps'
      ]"
  eric-enm-monitoring:
    enabled: true
    name: eric-enm-monitoring-eap7
    tag: 1.64.0-33
  waitForCertificatesContainer:
    enabled: true
    name: enm-wait-for-certificates-container
    tag: 1.52.0-33
imageCredentials:
  repoPath: proj-enm
  pullPolicy: Always
  pullSecret:
  registry:
    url:
eric-enm-common-helmchart-library:
  enabled: true
## Configure the service
service:
  name: filetransferservice
  sgname: filetransferservice
  annotations: {}
  labels:
  xmlMountPath: "/ericsson/credm/certReqMount"
  tlsMountPath: "/ericsson/credm/tlsMount"
  config:
    tcp:
    - portRange:
        vipPortRange:
          start: 10164
          end: 11863
        svcPortRange:
          start: 10164
          end: 11863
      algo: rr
      mode: nat
    - portRange:
        vipPortRange:
          start: 9920
          end: 9921
        svcPortRange:
          start: 9920
          end: 9921
      algo: rr
      mode: nat
    - portRange:
        vipPortRange:
          start: 21
          end: 22
        svcPortRange:
          start: 21
          end: 22
      algo: rr
      mode: nat
## Configure resource requests and limits
resources:
  requests:
    enabled: true
    memory: 4320Mi
  limits:
    enabled: true
    memory: 4620Mi
  monitoring:
    enabled: false
    requests:
      memory:
      cpu:
    limits:
      memory:
      cpu:
# StartupProbe Health Check configuration.
probes:
  container:
    startupProbe:
      enabled: true
      command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
      arguments: --exec_agents
      initialDelaySeconds: 10
      timeoutSeconds: 30
      periodSeconds: 30
      failureThreshold: 20
    livenessProbe:
      enabled: true
      command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
      arguments: --exec_agents
      initialDelaySeconds: 30
      timeoutSeconds: 30
      periodSeconds: 30
      failureThreshold: 2
    readinessProbe:
      enabled: true
      command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
      arguments: --exec_agents
      initialDelaySeconds: 10
      periodSeconds: 30
      timeoutSeconds: 30
      failureThreshold: 2
  monitoringcontainer:
    startupProbe:
      enabled: true
      command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
      arguments: --exec_agents
      initialDelaySeconds: 10
      timeoutSeconds: 30
      periodSeconds: 30
      failureThreshold: 20
    livenessProbe:
      enabled: true
      command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
      arguments: --exec_agents
      initialDelaySeconds: 30
      timeoutSeconds: 30
      periodSeconds: 30
      failureThreshold: 2
startupProbe:
  enabled: true
  command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
  arguments: --exec_agents
  initialDelaySeconds: 10
  timeoutSeconds: 30
  periodSeconds: 30
  failureThreshold: 20
# LivenessProbe Health Check configuration.
livenessProbe:
  enabled: true
  command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
  arguments: --exec_agents
  initialDelaySeconds: 30
  timeoutSeconds: 30
  periodSeconds: 30
  failureThreshold: 2
readinessProbe:
  enabled: true
  command: /ericsson/enm_healthcheck/bin/enm_healthcheck.py
  arguments: --exec_agents
  initialDelaySeconds: 10
  periodSeconds: 30
  timeoutSeconds: 30
  failureThreshold: 2
# Lifecycle hooks after container starts
lifecycle:
  handler:
    enabled: true
# Extra Annotations to be added to pod
podAnnotations: {}
## Tolerations for pod assignment
tolerations: []
## Affinity for pod assignment
affinity: requiredDuringSchedulingIgnoredDuringExecution
# Constrain which nodes your pod is eligible to be scheduled on
nodeAffinity: {}
priorityClassName: ""
## Node selector
nodeSelector: {}
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0
## Pod Disruption Budget is an indicator of the number of disruptions that can be tolerated at a given time.
podDisruptionBudget:
  maxUnavailable: 1
credmController:
  name: eric-enm-credm-controller
  port: 5001
jobs:
  jobAction: certrequest
  certRequest:
    imageName: enm-certrequestjob-container
    pullPolicy: Always
    tag: 1.52.0-33
    resources:
      requests:
        enabled: true
        cpu: 500m
        memory: 512Mi
      limits:
        enabled: true
        cpu: 1000m
        memory: 512Mi
securityContext:
  filetransferservice:
    allowPrivilegeEscalation: true
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    capabilities:
      drop:
      - all
      add:
      - DAC_OVERRIDE
      - SETGID
      - AUDIT_WRITE
      - SETUID
      - CHOWN
      - SETPCAP
      - FOWNER
      - FSETID
      - KILL
      - MKNOD
      - NET_RAW
      - NET_BIND_SERVICE
      - SYS_CHROOT
  monitoring:
    allowPrivilegeEscalation: true
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    capabilities:
      drop:
      - all
  waitInitContainer:
    allowPrivilegeEscalation: true
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    capabilities:
      drop:
      - all
  waitForCertificatesContainer:
    allowPrivilegeEscalation: true
    privileged: false
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    capabilities:
      drop:
      - all
